version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - mysql-data:/var/lib/mysql

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes_from:
      - datastore
      
  rails:
    build: .
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/rails_app
    links:
      - db

volumes:
  mysql-data:
    driver: local
